parameters:
  - name: runCI
    type: boolean
    default: false
    displayName: Run CI Build
  - name: skipPublishArtifacts
    type: boolean
    default: false
    displayName: skipPublishArtifacts   

stages:
    - stage: Build
      jobs:
      - job: Build
        displayName: Build_MVN
        variables:
            - template: var/variables_default.yaml@repo1            
        steps:
          - script: |
              echo "Run CI Build: ${{ parameters.runCI }}"
              echo "Skip Publish Artifacts: ${{ variables['skipPublishArtifacts'] }}"
            displayName: 'Print Parameters'

